sudo: false
language: c

addons:
  apt:
    packages:
    - libgmp-dev

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.stack
    - .stack-work

env:
  global:
  - SMT=z3
  - GHC=ghc-7.10.3

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- echo "resolver: ${GHC}" > stack.yaml
- travis_retry stack --no-terminal --install-ghc install cabal-install
- travis_retry curl "http://goto.ucsd.edu/~gridaphobe/$SMT" -o "${HOME}/.local/bin/$SMT"

install:
 - stack --no-terminal setup
 - stack --no-terminal ghc -- --version
 - stack --no-terminal update
 - stack --no-terminal solver --modify-stack-yaml
 - stack --no-terminal build --only-dependencies --test --no-run-tests

script:
 - stack --no-terminal build --test --no-run-tests --haddock
 - stack --no-terminal test

notifications:
  slack:
    rooms:
      secure: CPaI+XVTUSM9gLQefB8zSXazawNIaUnClS7FwaujPfM37hNBm5UIoiC80KBEe0KZKBr+Gt/LWq0zv506Zl/vILuPpVmfSi2BQ8zyyKCBbUrE/E0uBTjmT7wjaITf/mn3mqiLLcHbAVXI1bn7HzVvAq4S4eIpttgCapF7pbMhZCk=
    on_success: change
    on_failure: always
    on_start: never
