language: haskell
ghc: 7.6

notifications:
  email:
    - gridaphobe@gmail.com

install:
 - git clone git://github.com/gridaphobe/liquid-fixpoint.git /tmp/fixpoint
 - git clone git://github.com/gridaphobe/liquidhaskell.git /tmp/liquidhaskell
 - sudo apt-get update -qq
 - sudo apt-get install ocaml camlidl
 - pushd /tmp/fixpoint && git checkout origin/faststring && cabal install && popd
 - pushd /tmp/liquidhaskell && git checkout origin/faststring && cabal install && popd
 - cabal install --only-dependencies --enable-tests

# Here starts the actual work to be performed for the package under
# test; any command which exits with a non-zero exit code causes the
# build to fail.
script:
 # -v2 provides useful information for debugging
 - cabal install -v2

 # getting weird cabal mismatch error without the re-configure...
 - cabal configure --enable-tests && cabal build && ./dist/build/test/test

 # makes sure the .cabal file is reasonable
 - cabal check

 # tests that a source-distribution can be generated
 - cabal sdist

# EOF
